export * from './PlatformPage';
export * from './SubjectPage';
export { default as QuizPage } from "./QuizPage";
export * from './ForumPage';
export * from './ParentHome';
export { default as TeacherHome } from './TeacherHome';
export * from './AssignmentsPage';
//export * from './GuidesPage';
export { StudentPage } from './StudentPage';
export { default as ParentPage } from './ParentPage';
export * from './TeacherPage';
export * from './UserPage';
export * from './GuidesPage';
export * from './AdminHome';